#!/usr/bin/env python
# -*- coding=utf-8 -*-
# 
# Copyright © 2012 Jude Robinson (dotcode at gmail dot com | @dotcode)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from BeautifulSoup import BeautifulSoup
import urllib2
import re
from datetime import datetime as dt
import HTMLParser

# return the correct suffix for a date
def suffix(d):
    return 'th' if 11<=d<=13 else {1:'st',2:'nd',3:'rd'}.get(d%10, 'th')

# format a given date by adding the suffix
def custom_strftime(format, t):
    return t.strftime(format).replace('{S}', str(t.day) + suffix(t.day))

# todays date
now = dt.now()

# grab the listings page
page = urllib2.urlopen('http://www.kerbfood.com/kings-cross/')
soup = BeautifulSoup(page)

# find the listings panel
kerb = soup.find('div', 'rota_panel')
kerbList = kerb.find('ul')

# how many days left in the week
week = {'Mon': 5, 'Tue': 4, 'Wed': 3, 'Thu': 2, 'Fri': 1}
left = 5
for key, val in dict.items(week):
    if key == now.strftime('%a'):
    	left = val

# iterate over the remaining days of the week to find traders
for day in kerbList.findAll('li', recursive=False, limit=left):
	date = re.sub('^date-', '', day['id'])
	date = dt.strptime(date, '%Y-%m-%d')
	traders = custom_strftime('%a {S}', date) + ": "
	first = True
	for stall in day.findAll('li'):
		heading = stall.find('h4')
		h = HTMLParser.HTMLParser()
		name = h.unescape(heading.find('a').string)
		if first:
			traders = traders + name.title()
			first = False
		else:
			traders = traders + ", " + name.title()
	print traders